Add Tabs Component
ebth/design-system pull request #456
Opened 2021-01-06 23:02 UTC by mosherc

This PR adds the Tabs and TabsPanel to make a tabbed page component. The `Tabs` component takes in a few props for overarching features (like id, style, alignment, etc), while the `TabsPanel` is mainly for the label (what shows up in the tab button), children (content of the tab panel), and some tab specific data like if it's disabled. Tab labels and tab panel content can be pretty much any JSX code.

I think there might be more we could do with the tab buttons in terms of flex styling (filling the whole width or something), but we can flesh that out later.

## Default (left aligned)

<img width="826" alt="image" src="https://user-images.githubusercontent.com/7862535/103827842-dae0d580-5047-11eb-9f94-f2337b4b7d2c.png">

## Center aligned (with wrapping)

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7862535/103827958-154a7280-5048-11eb-83d5-8dcafd76754c.png">

## Right aligned (with wrapping)

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7862535/103827899-f9df6780-5047-11eb-8677-51bed75d18c3.png">

## Vertical

<img width="826" alt="image" src="https://user-images.githubusercontent.com/7862535/103827868-e8965b00-5047-11eb-9035-3a19aa346975.png">

## Vertical right aligned

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7862535/103827947-0f549180-5048-11eb-816e-964218e750fc.png">

## Underline style (like the live site)

<img width="629" alt="image" src="https://user-images.githubusercontent.com/7862535/103828212-9144ba80-5048-11eb-854e-5f366fcff93a.png">

2021-01-06 23:04 UTC, mosherc commented on src/molecules/Tabs/Tab.tsx
> +          {hasError && ( // Do we want to get rid of this? leftover copied code
@tonytrucco-CS some of this tab code is copied, so this was here and wasn't sure your opinion on keeping it or not.

2021-01-06 23:05 UTC, mosherc commented on src/molecules/Tabs/TabPanel.tsx
> +    tabIndex={0} // a11y docs mention this, do we want this?
@tonytrucco-CS this will allow focus on the div which has the content of the tab panel. The docs that you linked in the ticket mentioned that this is something you can do, and their example also had it, but wasn't sure if it's required and/or if you even want it.

2021-01-06 23:07 UTC, mosherc commented on src/molecules/Tabs/Tabs.style.tsx
> +  }
@tonytrucco-CS I added these focus styles based on the tabIndex being 0 for the panel. Let me know if you want this as well.

2021-01-07 14:38 UTC, tonytrucco-CS requested changes
A couple of issues:
* The tabs should not switch the content being viewed when using the arrow keys to navigate them. It should merely change focus to the next tab in the list, and I should have to use `space` or `enter` to activate that tab.
* Can we split out the `vertical` aspect into its own prop that's either `true` or `false`? With false as the default.
* Let's change the `default` value for `variant` to say `button` to help be more descriptive of what it looks like. We should maybe also consider changing the word `variant` to `style`.

2021-01-07 15:54 UTC, tonytrucco-CS commented on src/molecules/Tabs/TabPanel.tsx
> +    tabIndex={0} // a11y docs mention this, do we want this?
I don't think it's necessary when I'm clicking inside of the panel. It's useful when I'm tabbing around, but if we ever have interactive content inside of the panel then it's going to have this focus around it anytime I click inside of it.

2021-01-07 15:54 UTC, tonytrucco-CS commented on src/molecules/Tabs/Tab.tsx
> +          {hasError && ( // Do we want to get rid of this? leftover copied code
I don't think we need to have an error state for the tabs.

2021-01-07 15:55 UTC, tonytrucco-CS commented on src/molecules/Tabs/Tabs.style.tsx
> +  }
Yes, I do like it for the tabs themselves.

2021-01-07 17:02 UTC, mosherc commented
@tonytrucco-CS if we split out vertical into it's own prop, that means we could have vertical underlined buttons. Do you want that?

2021-01-07 17:06 UTC, tonytrucco-CS commented
@mosherc yeah, I think it's fine to have a vertical list of tabs with the underlined style. It's not entirely the style choice I would make, but it doesn't bother me if the option is available.

2021-01-07 18:31 UTC, jennyvb143 approved these changes
This is an awesome component! Nicely done!

2021-01-08 15:09 UTC, tonytrucco-CS approved these changes
Awesome. Nice work.

2021-01-08 15:10 UTC, merged